# Generated by Django 3.2.13 on 2022-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einheitmastrnummer', models.TextField(blank=True, max_length=256, null=True, unique=True)),
                ('land', models.TextField(blank=True, max_length=256, null=True)),
                ('bundesland', models.TextField(blank=True, max_length=256, null=True)),
                ('landkreis', models.TextField(blank=True, max_length=256, null=True)),
                ('gemeinde', models.TextField(blank=True, max_length=256, null=True)),
                ('gemeindeschluessel', models.TextField(blank=True, max_length=256, null=True)),
                ('postleitzahl', models.TextField(blank=True, max_length=256, null=True)),
                ('ort', models.TextField(blank=True, max_length=256, null=True)),
                ('breitengrad', models.FloatField(blank=True, null=True)),
                ('geplantesinbetriebnahmedatum', models.DateField(blank=True, null=True)),
                ('inbetriebnahmedatum', models.DateField(blank=True, null=True)),
                ('datumendgueltigestilllegung', models.DateField(blank=True, null=True)),
                ('datumbeginnvoruebergehendestilllegung', models.DateField(blank=True, null=True)),
                ('datumbeendigungvorlaeufigenstilllegung', models.DateField(blank=True, null=True)),
                ('datumwiederaufnahmebetrieb', models.DateField(blank=True, null=True)),
                ('einheitbetriebsstatus', models.TextField(blank=True, max_length=256, null=True)),
                ('energietraeger', models.TextField(blank=True, max_length=256, null=True)),
                ('bruttoleistung', models.FloatField(blank=True, null=True)),
                ('nettonennleistung', models.FloatField(blank=True, null=True)),
                ('anschlussanhoechstoderhochspannung', models.BooleanField(blank=True, null=True)),
                ('schwarzstartfaehigkeit', models.BooleanField(blank=True, null=True)),
                ('inselbetriebsfaehigkeit', models.BooleanField(blank=True, null=True)),
                ('fernsteuerbarkeitnb', models.BooleanField(blank=True, null=True)),
                ('fernsteuerbarkeitdv', models.BooleanField(blank=True, null=True)),
                ('fernsteuerbarkeitdr', models.BooleanField(blank=True, null=True)),
                ('einspeisungsart', models.TextField(blank=True, max_length=256, null=True)),
                ('praequalifiziertfuerregelenergie', models.BooleanField(blank=True, null=True)),
                ('solar_lage', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_leistungsbegrenzung', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_hauptausrichtung', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_hauptausrichtungneigungswinkel', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_inanspruchgenommeneflaeche', models.FloatField(blank=True, null=True)),
                ('solar_artderflaeche', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_inanspruchgenommeneackerflaeche', models.FloatField(blank=True, null=True)),
                ('solar_nutzungsbereich', models.TextField(blank=True, max_length=256, null=True)),
                ('solar_artderflaecheids', models.TextField(blank=True, max_length=256, null=True)),
                ('biomass_hauptbrennstoff', models.TextField(blank=True, max_length=256, null=True)),
                ('biomass_biomasseart', models.TextField(blank=True, max_length=256, null=True)),
                ('biomass_technologie', models.TextField(blank=True, max_length=256, null=True)),
                ('hydro_artderwasserkraftanlage', models.TextField(blank=True, max_length=256, null=True)),
                ('hydro_minderungstromerzeugung', models.BooleanField(blank=True, null=True)),
                ('hydro_nettonennleistungdeutschland', models.FloatField(blank=True, null=True)),
                ('hydro_artdeszuflusses', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_lage', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_seelage', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_clusterostsee', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_clusternordsee', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_technologie', models.TextField(blank=True, max_length=256, null=True)),
                ('wind_nabenhoehe', models.FloatField(blank=True, null=True)),
                ('wind_rotordurchmesser', models.FloatField(blank=True, null=True)),
                ('wind_wassertiefe', models.FloatField(blank=True, null=True)),
                ('wind_kuestenentfernung', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'energy_sources',
                'managed': True,
            },
        ),
    ]
