# Generated by Django 3.2.13 on 2022-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('net_nominal_capacity', models.FloatField()),
                ('zip_code', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('energy_source', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'monthly_timeline',
                'managed': False,
            },
        ),
    ]
