# Generated by Django 3.2.13 on 2022-06-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SolarExtended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "einheitmastrnummer",
                    models.TextField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("land", models.TextField(blank=True, max_length=256, null=True)),
                ("bundesland", models.TextField(blank=True, max_length=256, null=True)),
                ("landkreis", models.TextField(blank=True, max_length=256, null=True)),
                ("gemeinde", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "gemeindeschluessel",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "postleitzahl",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("ort", models.TextField(blank=True, max_length=256, null=True)),
                ("breitengrad", models.FloatField(blank=True, null=True)),
                (
                    "geplantesinbetriebnahmedatum",
                    models.DateField(blank=True, null=True),
                ),
                ("inbetriebnahmedatum", models.DateField(blank=True, null=True)),
                (
                    "datumendgueltigestilllegung",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "datumbeginnvoruebergehendestilllegung",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "datumbeendigungvorlaeufigenstilllegung",
                    models.DateField(blank=True, null=True),
                ),
                ("datumwiederaufnahmebetrieb", models.DateField(blank=True, null=True)),
                (
                    "einheitbetriebsstatus",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("bruttoleistung", models.FloatField(blank=True, null=True)),
                ("nettonennleistung", models.FloatField(blank=True, null=True)),
                (
                    "anschlussanhoechstoderhochspannung",
                    models.BooleanField(blank=True, null=True),
                ),
                ("schwarzstartfaehigkeit", models.BooleanField(blank=True, null=True)),
                ("inselbetriebsfaehigkeit", models.BooleanField(blank=True, null=True)),
                ("fernsteuerbarkeitnb", models.BooleanField(blank=True, null=True)),
                ("fernsteuerbarkeitdv", models.BooleanField(blank=True, null=True)),
                ("fernsteuerbarkeitdr", models.BooleanField(blank=True, null=True)),
                (
                    "einspeisungsart",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "praequalifiziertfuerregelenergie",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "gemeinsamerwechselrichtermitspeicher",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                ("lage", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "leistungsbegrenzung",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "hauptausrichtung",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "hauptausrichtungneigungswinkel",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "inanspruchgenommeneflaeche",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "artderflaeche",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "inanspruchgenommeneackerflaeche",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "nutzungsbereich",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
                (
                    "artderflaecheids",
                    models.TextField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "db_table": "solar_extended",
                "managed": True,
            },
        ),
    ]
