# Generated by Django 3.2.13 on 2022-11-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastr_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monthlytimeline',
            table='monthly_timeline',
        ),
    ]
