# Generated by Django 3.2.13 on 2023-11-29 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastr_data', '0002_alter_monthlytimeline_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_nr', models.CharField(max_length=200, verbose_name='Unit Nr.')),
                ('municipality_key', models.CharField(max_length=200, verbose_name='Municipality Key')),
                ('municipality', models.CharField(max_length=200, verbose_name='Municipality')),
                ('county', models.CharField(max_length=200, verbose_name='County')),
                ('state', models.CharField(blank=True, max_length=200, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=7, verbose_name='Zip-Code')),
                ('start_up_date', models.DateTimeField(default=None, verbose_name='Start Up Date')),
                ('date', models.DateTimeField(default=None, verbose_name='Corrected Date')),
                ('pv_net_nominal_capacity', models.FloatField(verbose_name='PV net nominal capacity')),
                ('wind_net_nominal_capacity', models.FloatField(verbose_name='Wind net nominal capacity')),
                ('biomass_net_nominal_capacity', models.FloatField(verbose_name='Biomass net nominal capacity')),
                ('hydro_net_nominal_capacity', models.FloatField(verbose_name='Hydro net nominal capacity')),
                ('storage_net_nominal_capacity', models.FloatField(verbose_name='Storage net nominal capacity')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location')),
            ],
            options={
                'db_table': 'energy_units',
                'managed': False,
            },
        ),
    ]
