ALTER TABLE solar_extended
    DROP COLUMN DatenQuelle,
    DROP COLUMN DatumDownload,
    DROP COLUMN NetzbetreiberMastrNummer,
    DROP COLUMN DatumLetzteAktualisierung,
    DROP COLUMN Registrierungsdatum,
    DROP COLUMN LokationMastrNummer,
    DROP COLUMN NetzbetreiberpruefungStatus,
    DROP COLUMN NetzbetreiberpruefungDatum,
    DROP COLUMN AnlagenbetreiberMastrNummer,
    DROP COLUMN Gemarkung,
    DROP COLUMN FlurFlurstuecknummern,
    DROP COLUMN Strasse,
    DROP COLUMN StrasseNichtGefunden,
    DROP COLUMN Hausnummer,
    DROP COLUMN HausnummerNichtGefunden,
    DROP COLUMN Adresszusatz,
    DROP COLUMN Laengengrad,
    DROP COLUMN UtmZonenwert,
    DROP COLUMN UtmEast,
    DROP COLUMN UtmNorth,
    DROP COLUMN GaussKruegerHoch,
    DROP COLUMN GaussKruegerRechts,
    DROP COLUMN Meldedatum,
    DROP COLUMN EinheitSystemstatus,
    DROP COLUMN BestandsanlageMastrNummer,
    DROP COLUMN AltAnlagenbetreiberMastrNummer,
    DROP COLUMN DatumDesBetreiberwechsels,
    DROP COLUMN DatumRegistrierungDesBetreiberwechsels,
    DROP COLUMN StatisikFlag,
    DROP COLUMN NameStromerzeugungseinheit,
    DROP COLUMN Weic,
    DROP COLUMN WeicDisplayName,
    DROP COLUMN Kraftwerksnummer,
    DROP COLUMN GenMastrNummer,
    DROP COLUMN Hausnummer_nv,
    DROP COLUMN Weic_nv,
    DROP COLUMN Kraftwerksnummer_nv,
    DROP COLUMN NichtVorhandenInMigriertenEinheiten,
    DROP COLUMN Einsatzverantwortlicher,
    DROP COLUMN zugeordneteWirkleistungWechselrichter,
    DROP COLUMN GemeinsamerWechselrichterMitSpeicher,
    DROP COLUMN AnzahlModule,
    DROP COLUMN EinheitlicheAusrichtungUndNeigungswinkel,
    DROP COLUMN Nebenausrichtung,
    DROP COLUMN NebenausrichtungNeigungswinkel,
    DROP COLUMN EegMastrNummer;

ALTER TABLE biomass_extended
    DROP COLUMN DatenQuelle,
    DROP COLUMN DatumDownload,
    DROP COLUMN NetzbetreiberMastrNummer,
    DROP COLUMN DatumLetzteAktualisierung,
    DROP COLUMN Registrierungsdatum,
    DROP COLUMN LokationMastrNummer,
    DROP COLUMN NetzbetreiberpruefungStatus,
    DROP COLUMN NetzbetreiberpruefungDatum,
    DROP COLUMN AnlagenbetreiberMastrNummer,
    DROP COLUMN Gemarkung,
    DROP COLUMN FlurFlurstuecknummern,
    DROP COLUMN Strasse,
    DROP COLUMN StrasseNichtGefunden,
    DROP COLUMN Hausnummer,
    DROP COLUMN HausnummerNichtGefunden,
    DROP COLUMN Adresszusatz,
    DROP COLUMN Laengengrad,
    DROP COLUMN UtmZonenwert,
    DROP COLUMN UtmEast,
    DROP COLUMN UtmNorth,
    DROP COLUMN GaussKruegerHoch,
    DROP COLUMN GaussKruegerRechts,
    DROP COLUMN Meldedatum,
    DROP COLUMN EinheitSystemstatus,
    DROP COLUMN BestandsanlageMastrNummer,
    DROP COLUMN AltAnlagenbetreiberMastrNummer,
    DROP COLUMN DatumDesBetreiberwechsels,
    DROP COLUMN DatumRegistrierungDesBetreiberwechsels,
    DROP COLUMN StatisikFlag,
    DROP COLUMN NameStromerzeugungseinheit,
    DROP COLUMN Weic,
    DROP COLUMN WeicDisplayName,
    DROP COLUMN Kraftwerksnummer,
    DROP COLUMN GenMastrNummer,
    DROP COLUMN Hausnummer_nv,
    DROP COLUMN Weic_nv,
    DROP COLUMN Kraftwerksnummer_nv,
    DROP COLUMN NichtVorhandenInMigriertenEinheiten,
    DROP COLUMN Einsatzverantwortlicher,
    DROP COLUMN EegMastrNummer,
    DROP COLUMN KwkMastrNummer;

ALTER TABLE hydro_extended
    DROP COLUMN DatenQuelle,
    DROP COLUMN DatumDownload,
    DROP COLUMN NetzbetreiberMastrNummer,
    DROP COLUMN DatumLetzteAktualisierung,
    DROP COLUMN Registrierungsdatum,
    DROP COLUMN LokationMastrNummer,
    DROP COLUMN NetzbetreiberpruefungStatus,
    DROP COLUMN NetzbetreiberpruefungDatum,
    DROP COLUMN AnlagenbetreiberMastrNummer,
    DROP COLUMN Gemarkung,
    DROP COLUMN FlurFlurstuecknummern,
    DROP COLUMN Strasse,
    DROP COLUMN StrasseNichtGefunden,
    DROP COLUMN Hausnummer,
    DROP COLUMN HausnummerNichtGefunden,
    DROP COLUMN Adresszusatz,
    DROP COLUMN Laengengrad,
    DROP COLUMN UtmZonenwert,
    DROP COLUMN UtmEast,
    DROP COLUMN UtmNorth,
    DROP COLUMN GaussKruegerHoch,
    DROP COLUMN GaussKruegerRechts,
    DROP COLUMN Meldedatum,
    DROP COLUMN EinheitSystemstatus,
    DROP COLUMN BestandsanlageMastrNummer,
    DROP COLUMN AltAnlagenbetreiberMastrNummer,
    DROP COLUMN DatumDesBetreiberwechsels,
    DROP COLUMN DatumRegistrierungDesBetreiberwechsels,
    DROP COLUMN StatisikFlag,
    DROP COLUMN NameStromerzeugungseinheit,
    DROP COLUMN Weic,
    DROP COLUMN WeicDisplayName,
    DROP COLUMN Kraftwerksnummer,
    DROP COLUMN GenMastrNummer,
    DROP COLUMN Hausnummer_nv,
    DROP COLUMN Weic_nv,
    DROP COLUMN Kraftwerksnummer_nv,
    DROP COLUMN NichtVorhandenInMigriertenEinheiten,
    DROP COLUMN Einsatzverantwortlicher,
    DROP COLUMN NameKraftwerk,
    DROP COLUMN AnzeigeEinerStilllegung,
    DROP COLUMN ArtDerStilllegung,
    DROP COLUMN DatumBeginnVorlaeufigenOderEndgueltigenStilllegung,
    DROP COLUMN BestandteilGrenzkraftwerk,
    DROP COLUMN EegMastrNummer;

ALTER TABLE wind_extended
    DROP COLUMN DatenQuelle,
    DROP COLUMN DatumDownload,
    DROP COLUMN NetzbetreiberMastrNummer,
    DROP COLUMN DatumLetzteAktualisierung,
    DROP COLUMN Registrierungsdatum,
    DROP COLUMN LokationMastrNummer,
    DROP COLUMN NetzbetreiberpruefungStatus,
    DROP COLUMN NetzbetreiberpruefungDatum,
    DROP COLUMN AnlagenbetreiberMastrNummer,
    DROP COLUMN Gemarkung,
    DROP COLUMN FlurFlurstuecknummern,
    DROP COLUMN Strasse,
    DROP COLUMN StrasseNichtGefunden,
    DROP COLUMN Hausnummer,
    DROP COLUMN HausnummerNichtGefunden,
    DROP COLUMN Adresszusatz,
    DROP COLUMN Laengengrad,
    DROP COLUMN UtmZonenwert,
    DROP COLUMN UtmEast,
    DROP COLUMN UtmNorth,
    DROP COLUMN GaussKruegerHoch,
    DROP COLUMN GaussKruegerRechts,
    DROP COLUMN Meldedatum,
    DROP COLUMN EinheitSystemstatus,
    DROP COLUMN BestandsanlageMastrNummer,
    DROP COLUMN AltAnlagenbetreiberMastrNummer,
    DROP COLUMN DatumDesBetreiberwechsels,
    DROP COLUMN DatumRegistrierungDesBetreiberwechsels,
    DROP COLUMN StatisikFlag,
    DROP COLUMN NameStromerzeugungseinheit,
    DROP COLUMN Weic,
    DROP COLUMN WeicDisplayName,
    DROP COLUMN Kraftwerksnummer,
    DROP COLUMN GenMastrNummer,
    DROP COLUMN Hausnummer_nv,
    DROP COLUMN Weic_nv,
    DROP COLUMN Kraftwerksnummer_nv,
    DROP COLUMN NichtVorhandenInMigriertenEinheiten,
    DROP COLUMN Einsatzverantwortlicher,
    DROP COLUMN NameWindpark,
    DROP COLUMN Hersteller,
    DROP COLUMN HerstellerId,
    DROP COLUMN Typenbezeichnung,
    DROP COLUMN Rotorblattenteisungssystem,
    DROP COLUMN AuflageAbschaltungLeistungsbegrenzung,
    DROP COLUMN AuflagenAbschaltungSchallimmissionsschutzNachts,
    DROP COLUMN AuflagenAbschaltungSchallimmissionsschutzTagsueber,
    DROP COLUMN AuflagenAbschaltungSchattenwurf,
    DROP COLUMN AuflagenAbschaltungTierschutz,
    DROP COLUMN AuflagenAbschaltungEiswurf,
    DROP COLUMN AuflagenAbschaltungSonstige,
    DROP COLUMN EegMastrNummer;

ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN lage TO solar_lage;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN leistungsbegrenzung TO solar_leistungsbegrenzung;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN hauptausrichtung TO solar_hauptausrichtung;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN hauptausrichtungneigungswinkel TO solar_hauptausrichtungneigungswinkel;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN inanspruchgenommeneflaeche TO solar_inanspruchgenommeneflaeche;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN artderflaeche TO solar_artderflaeche;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN inanspruchgenommeneackerflaeche TO solar_inanspruchgenommeneackerflaeche;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN nutzungsbereich TO solar_nutzungsbereich;
ALTER TABLE IF EXISTS solar_extended
    RENAME COLUMN artderflaecheids TO solar_artderflaecheids;


ALTER TABLE IF EXISTS solar_extended
    ADD COLUMN biomass_hauptbrennstoff text COLLATE pg_catalog."default",
    ADD COLUMN biomass_biomasseart     text COLLATE pg_catalog."default",
    ADD COLUMN biomass_technologie     text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS solar_extended
    ADD COLUMN hydro_artderwasserkraftanlage      text COLLATE pg_catalog."default",
    ADD COLUMN hydro_minderungstromerzeugung      boolean,
    ADD COLUMN hydro_nettonennleistungdeutschland double precision,
    ADD COLUMN hydro_artdeszuflusses              text COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS solar_extended
    ADD COLUMN wind_lage              text COLLATE pg_catalog."default",
    ADD COLUMN wind_seelage           text COLLATE pg_catalog."default",
    ADD COLUMN wind_clusterostsee     text COLLATE pg_catalog."default",
    ADD COLUMN wind_clusternordsee    text COLLATE pg_catalog."default",
    ADD COLUMN wind_technologie       text COLLATE pg_catalog."default",
    ADD COLUMN wind_nabenhoehe        double precision,
    ADD COLUMN wind_rotordurchmesser  double precision,
    ADD COLUMN wind_wassertiefe       double precision,
    ADD COLUMN wind_kuestenentfernung double precision;

INSERT INTO solar_extended (einheitmastrnummer, land, bundesland, landkreis, gemeinde, gemeindeschluessel, postleitzahl,
                            ort, breitengrad, geplantesinbetriebnahmedatum, inbetriebnahmedatum,
                            datumendgueltigestilllegung, datumbeginnvoruebergehendestilllegung,
                            datumbeendigungvorlaeufigenstilllegung, datumwiederaufnahmebetrieb, einheitbetriebsstatus,
                            energietraeger, bruttoleistung, nettonennleistung, anschlussanhoechstoderhochspannung,
                            schwarzstartfaehigkeit, inselbetriebsfaehigkeit, fernsteuerbarkeitnb, fernsteuerbarkeitdv,
                            fernsteuerbarkeitdr, einspeisungsart, praequalifiziertfuerregelenergie,
                            biomass_hauptbrennstoff, biomass_biomasseart, biomass_technologie)
SELECT einheitmastrnummer,
       land,
       bundesland,
       landkreis,
       gemeinde,
       gemeindeschluessel,
       postleitzahl,
       ort,
       breitengrad,
       geplantesinbetriebnahmedatum,
       inbetriebnahmedatum,
       datumendgueltigestilllegung,
       datumbeginnvoruebergehendestilllegung,
       datumbeendigungvorlaeufigenstilllegung,
       datumwiederaufnahmebetrieb,
       einheitbetriebsstatus,
       energietraeger,
       bruttoleistung,
       nettonennleistung,
       anschlussanhoechstoderhochspannung,
       schwarzstartfaehigkeit,
       inselbetriebsfaehigkeit,
       fernsteuerbarkeitnb,
       fernsteuerbarkeitdv,
       fernsteuerbarkeitdr,
       einspeisungsart,
       praequalifiziertfuerregelenergie,
       hauptbrennstoff,
       biomasseart,
       technologie
FROM biomass_extended;

INSERT INTO solar_extended (einheitmastrnummer, land, bundesland, landkreis, gemeinde, gemeindeschluessel, postleitzahl,
                            ort, breitengrad, geplantesinbetriebnahmedatum, inbetriebnahmedatum,
                            datumendgueltigestilllegung, datumbeginnvoruebergehendestilllegung,
                            datumbeendigungvorlaeufigenstilllegung, datumwiederaufnahmebetrieb, einheitbetriebsstatus,
                            energietraeger, bruttoleistung, nettonennleistung, anschlussanhoechstoderhochspannung,
                            schwarzstartfaehigkeit, inselbetriebsfaehigkeit, fernsteuerbarkeitnb, fernsteuerbarkeitdv,
                            fernsteuerbarkeitdr, einspeisungsart, praequalifiziertfuerregelenergie,
                            hydro_artderwasserkraftanlage, hydro_minderungstromerzeugung,
                            hydro_nettonennleistungdeutschland, hydro_artdeszuflusses)
SELECT einheitmastrnummer,
       land,
       bundesland,
       landkreis,
       gemeinde,
       gemeindeschluessel,
       postleitzahl,
       ort,
       breitengrad,
       geplantesinbetriebnahmedatum,
       inbetriebnahmedatum,
       datumendgueltigestilllegung,
       datumbeginnvoruebergehendestilllegung,
       datumbeendigungvorlaeufigenstilllegung,
       datumwiederaufnahmebetrieb,
       einheitbetriebsstatus,
       energietraeger,
       bruttoleistung,
       nettonennleistung,
       anschlussanhoechstoderhochspannung,
       schwarzstartfaehigkeit,
       inselbetriebsfaehigkeit,
       fernsteuerbarkeitnb,
       fernsteuerbarkeitdv,
       fernsteuerbarkeitdr,
       einspeisungsart,
       praequalifiziertfuerregelenergie,
       artderwasserkraftanlage,
       minderungstromerzeugung,
       nettonennleistungdeutschland,
       artdeszuflusses
FROM hydro_extended;

INSERT INTO solar_extended (einheitmastrnummer, land, bundesland, landkreis, gemeinde, gemeindeschluessel, postleitzahl,
                            ort, breitengrad, geplantesinbetriebnahmedatum, inbetriebnahmedatum,
                            datumendgueltigestilllegung, datumbeginnvoruebergehendestilllegung,
                            datumbeendigungvorlaeufigenstilllegung, datumwiederaufnahmebetrieb, einheitbetriebsstatus,
                            energietraeger, bruttoleistung, nettonennleistung, anschlussanhoechstoderhochspannung,
                            schwarzstartfaehigkeit, inselbetriebsfaehigkeit, fernsteuerbarkeitnb, fernsteuerbarkeitdv,
                            fernsteuerbarkeitdr, einspeisungsart, praequalifiziertfuerregelenergie,
                            wind_lage, wind_seelage, wind_clusterostsee,
                            wind_clusternordsee, wind_technologie, wind_nabenhoehe, wind_rotordurchmesser,
                            wind_wassertiefe, wind_kuestenentfernung)
SELECT einheitmastrnummer,
       land,
       bundesland,
       landkreis,
       gemeinde,
       gemeindeschluessel,
       postleitzahl,
       ort,
       breitengrad,
       geplantesinbetriebnahmedatum,
       inbetriebnahmedatum,
       datumendgueltigestilllegung,
       datumbeginnvoruebergehendestilllegung,
       datumbeendigungvorlaeufigenstilllegung,
       datumwiederaufnahmebetrieb,
       einheitbetriebsstatus,
       energietraeger,
       bruttoleistung,
       nettonennleistung,
       anschlussanhoechstoderhochspannung,
       schwarzstartfaehigkeit,
       inselbetriebsfaehigkeit,
       fernsteuerbarkeitnb,
       fernsteuerbarkeitdv,
       fernsteuerbarkeitdr,
       einspeisungsart,
       praequalifiziertfuerregelenergie,
       lage,
       seelage,
       clusterostsee,
       clusternordsee,
       technologie,
       nabenhoehe,
       rotordurchmesser,
       wassertiefe,
       kuestenentfernung
FROM wind_extended;

DROP TABLE biomass_extended, hydro_extended, wind_extended;
ALTER TABLE solar_extended RENAME TO energy_sources;
